### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by devchakraborty** [matthewn4444/jobmine-plus-extension#5]
Using Chrome 45.0.2454.85 (64-bit) on OS X 10.10.5.

![image](https://cloud.githubusercontent.com/assets/2321559/9857407/4a9a8278-5ae8-11e5-8632-02060137887c.png)

And downloading the script and dragging to chrome://extensions does not show the installation dialog.

**Comment by matthewn4444** [comment]
Install with chrome extension tampermonkey (https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en). This is Google's security.
