### ISSUE TITLE
Job Search not working

### ISSUE THREAD

**Issue by sarimzafar** [matthewn4444/jobmine-plus-extension#8]
Unable to perform Job Search for the Fall 2016 term. Please refer to the uploaded screenshot.

![search_not_working](https://cloud.githubusercontent.com/assets/8084074/15059668/34076612-12f2-11e6-96d8-7f5b33a051b9.PNG)

**Comment by matthewn4444** [comment]
#11 Tracked in here, someone was kind enough to work on a pull request.
