### ISSUE TITLE
Loading Job Search dialog boxes from both Jobmine plus and Jobmine.

### ISSUE THREAD

**Issue by sarimzafar** [matthewn4444/jobmine-plus-extension#9]
When directed to the Job Search page, it shows the search dialog boxes for both Jobmine and Jobmine plus. 

Please refer to the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/8084074/15059710/807f8c36-12f2-11e6-89cc-816ba0c4263c.png)

**Comment by matthewn4444** [comment]
#11 Tracked in here, someone was kind enough to work on a pull request.
